name: ecg_env
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - boto3=1.29.1
  - botocore=1.32.1
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - flask=2.2.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_server=1.13.5
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.4.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclassic=1.0.0
  - nbconvert=5.5.0
  - nbformat=5.1.3
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.3.0
  - openssl=3.0.12
  - packaging=23.1
  - pandas=2.1.1
  - pandas-datareader=0.10.0
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - s3transfer=0.7.0
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - altair==5.1.2
      - astunparse==1.6.3
      - blinker==1.7.0
      - cachetools==5.3.2
      - flatbuffers==23.5.26
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-ai-generativelanguage==0.3.3
      - google-api-core==2.14.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - google-generativeai==0.2.2
      - google-pasta==0.2.0
      - googleapis-common-protos==1.61.0
      - grpcio==1.59.3
      - grpcio-status==1.59.3
      - keras==2.15.0
      - libclang==16.0.6
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - proto-plus==1.22.3
      - protobuf==4.23.4
      - pyarrow==14.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydeck==0.8.1b0
      - pyqt5-sip==12.11.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - smmap==5.0.1
      - streamlit==1.28.2
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-macos==2.15.0
      - tensorflow-metal==1.1.0
      - termcolor==2.3.0
      - toolz==0.12.0
      - tzlocal==5.2
      - validators==0.22.0
      - wrapt==1.14.1

